export const PRODUCT_ADD_REQUEST = "PRODUCT_ADD_REQUEST"
export const PRODUCT_ADD_RESPONSE = "PRODUCT_ADD_RESPONSE"
export const PRODUCT_ADD_FAIL = "PRODUCT_ADD_FAIL"

export const PRODUCT_LIST_REQUEST = "PRODUCT_LIST_REQUEST"
export const PRODUCT_LIST_RESPONSE = "PRODUCT_LIST_RESPONSE"
export const PRODUCT_LIST_FAIL = "PRODUCT_LIST_FAIL"

export const PRODUCT_DETAILS_REQUEST = "PRODUCT_DETAILS_REQUEST"
export const PRODUCT_DETAILS_RESPONSE = "PRODUCT_DETAILS_RESPONSE"
export const PRODUCT_DETAILS_FAIL = "PRODUCT_DETAILS_FAIL"