// Register
export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const USER_REGISTER_RESPONSE = "USER_REGISTER_RESPONSE";
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL";
// Login
export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_RESPONSE = "USER_LOGIN_RESPONSE";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";